# Generated by Django 5.1.3 on 2024-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeweb', '0002_remove_application_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
